# ElasticNet Regression

In [3]:
import numpy as np
import pandas as pd
from sklearn.linear_model import Ridge, Lasso, ElasticNet
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn import model_selection
import matplotlib.pyplot as plt
from sklearn.linear_model import RidgeCV, LassoCV, ElasticNetCV

In [4]:
df = pd.read_csv("Hitters.csv")
df = df.dropna()
dms = pd.get_dummies(df[["League", "Division", "NewLeague"]]) # kategorig değişkenleri onehot encoding metoduyla dummy değişkenlere çevirdik
y = df["Salary"]
X_ = df.drop(["Salary", "League", "Division", "NewLeague"], axis=1).astype("float64")
X = pd.concat([X_, dms[["League_N", "Division_W", "NewLeague_N"]]], axis=1)
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=.25,
                                                    random_state=42)

df.head()

AtBat  Hits  HmRun  Runs  RBI  Walks  Years  CAtBat  CHits  CHmRun  CRuns  \
1    315    81      7    24   38     39     14    3449    835      69    321   
2    479   130     18    66   72     76      3    1624    457      63    224   
3    496   141     20    65   78     37     11    5628   1575     225    828   
4    321    87     10    39   42     30      2     396    101      12     48   
5    594   169      4    74   51     35     11    4408   1133      19    501   

   CRBI  CWalks League Division  PutOuts  Assists  Errors  Salary NewLeague  
1   414     375      N        W      632       43      10   475.0         N  
2   266     263      A        W      880       82      14   480.0         A  
3   838     354      N        E      200       11       3   500.0         N  
4    46      33      N        E      805       40       4    91.5         N  
5   336     194      A        W      282      421      25   750.0         A

In [5]:
enetModel = ElasticNet().fit(X_train, y_train)

C:\Users\ertug\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 8487984.799367309, tolerance: 3898.686956380658
  model = cd_fast.enet_coordinate_descent(


In [6]:
enetModel.intercept_

-6.46595560211199

In [7]:
enetModel.coef_

array([ -1.86256172,   8.70489065,   5.10426375,  -2.89875799,
        -1.28642985,   5.24343682,   6.04480276,  -0.14701495,
        -0.21566628,  -0.7897201 ,   1.80813117,   0.80914508,
        -0.61262382,   0.26816203,   0.27172387,  -0.36530729,
        19.2186222 , -31.16586592,   8.98369938])

### Tahmin

In [46]:
enetModel.predict(X_train)

array([ 325.74706292,  776.06632333,  522.86508419,  107.64091955,
        449.03139566,  997.76095723,   99.78828622,  311.33763086,
        418.50335021,  879.9502608 , 1628.05423879,  831.63172575,
        909.34196881,  715.67274292,  601.33595953,  657.40417507,
       1068.2110763 ,  149.6849625 ,  190.40513329,  385.31235163,
        752.37991572, 1022.76166475,  486.94874949,  349.7945189 ,
         69.28225147,  783.98489255,  551.11613877,  205.84644387,
        367.25234577,  303.22135065,   98.44933333,  533.19866378,
       1000.16419322,  245.20490159,  448.10920305,  401.93188524,
        457.71559572,  713.00914559,  333.18157434,  235.45584771,
        210.52615243,  309.20890759,  190.6560382 ,  183.01443111,
        238.19688018, 1080.44877923,  380.19569305,  551.45922356,
        278.3820838 ,  338.53829531,  427.9529666 ,  476.71228336,
        297.09609267,  435.8113557 ,  592.18850471,  320.60291497,
        510.97484699,  698.77992314,  218.04297483, 1535.95190

In [47]:
enetModel.predict(X_test)

array([ 577.79111731,  617.33202224, 1031.39113156,  364.95861575,
        489.51894393,  300.74185842,  604.522666  ,  465.34678732,
        901.44473965,  703.20357123,  702.9157117 ,  931.50283407,
        184.87939803,  385.14973787,  325.38944176,  546.99346574,
        774.28001821,  101.83114992, 1250.86758812,  370.67651244,
        442.05734523,  781.17288513,  578.63736538,  609.31927808,
        608.31719597,  227.46556223,  921.85505228,  301.1202457 ,
        386.31721051,  133.61143326,  162.28505608,   88.29793182,
        359.9068418 ,  422.51268445,  265.8663769 ,  355.70450908,
       1329.36312363,  125.05506935,   82.74580002,  269.17483075,
        117.13319397,  274.13484779,  648.4957249 ,  409.47065999,
        846.27919406,  712.04817644,  341.10596674,  368.24259678,
        305.70477656,  680.05724792,  716.13640636,  295.93204262,
        773.06445823,  249.28224916,  221.46794589,  541.2713245 ,
        611.50212372,  770.80228024,  168.45143906, 1159.05660

In [48]:
y_pred = enetModel.predict(X_test)

In [49]:
RMSE = np.sqrt(mean_squared_error(y_test, y_pred)) 
RMSE

357.1676548181245

In [50]:
r2_score(y_test, y_pred)

0.4107022246932689

### Model Tuning

In [51]:
alphas__ = pow(10, np.linspace(10, -2, 100))*.5

In [52]:
enetCVModel = ElasticNetCV(alphas=alphas__, cv=10).fit(X_train, y_train)

C:\Users\ertug\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:525: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3249.9483051374555, tolerance: 3241.4244490642723
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\ertug\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:525: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 4337.003150258213, tolerance: 3241.4244490642723
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\ertug\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:525: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 5751.424798319116, tolerance: 3241.4244490642723
  model = cd_fast.enet_coordinate_descent_gram(
C:\Users\ertug\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:525

In [53]:
enetCVModel.alpha_

5748.784976988678

In [54]:
enetCVModel.intercept_

-31.46312122564109

In [55]:
enetCVModel.coef_

array([ 0.61111381,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        , -0.        ,  0.        ,  0.11212622,  0.        ,
        0.25252702,  0.18656722,  0.00444355,  0.30988823,  0.        ,
       -0.        ,  0.        , -0.        ,  0.        ])

### Final Model

In [59]:
enetTuned = ElasticNet(alpha = enetCVModel.alpha_).fit(X_train, y_train)

In [60]:
y_pred = enetTuned.predict(X_test)

In [61]:
RMSE_Tuned=np.sqrt(mean_squared_error(y_test, y_pred))
RMSE_Tuned

393.9753065850553

In [62]:
?ElasticNet

Init signature:
ElasticNet(
    alpha=1.0,
    *,
    l1_ratio=0.5,
    fit_intercept=True,
    normalize=False,
    precompute=False,
    max_iter=1000,
    copy_X=True,
    tol=0.0001,
    warm_start=False,
    positive=False,
    random_state=None,
    selection='cyclic',
)
Docstring:     
Linear regression with combined L1 and L2 priors as regularizer.

Minimizes the objective function::

        1 / (2 * n_samples) * ||y - Xw||^2_2
        + alpha * l1_ratio * ||w||_1
        + 0.5 * alpha * (1 - l1_ratio) * ||w||^2_2

If you are interested in controlling the L1 and L2 penalty
separately, keep in mind that this is equivalent to::

        a * L1 + b * L2

where::

        alpha = a + b and l1_ratio = a / (a + b)

The parameter l1_ratio corresponds to alpha in the glmnet R package while
alpha corresponds to the lambda parameter in glmnet. Specifically, l1_ratio
= 1 is the lasso penalty. Currently, l1_ratio <= 0.01 is not reliable,
unless you supply your own sequence of alpha.

Read